FROM nginx

# https://www.reddit.com/r/docker/comments/99wsmt/simplest_way_to_serve_a_static_website/
# FROM nginx:alpine


# cd static-sites hello

# docker run -p 80:80 static-sites-hello
# COPY public/ /var/share/nginx/html


# https://hub.docker.com/_/nginx


# docker run --name some-nginx -v /some/content:/usr/share/nginx/html:ro -d nginx

# https://www.digitalocean.com/community/tutorials/deploy-react-application-with-nginx-on-ubuntu


# COPY static-html-directory /usr/share/nginx/html

#  docker build . -t static-sites-hello
#  docker run static-sites-hello -d -p 8080:80
# curl localhost:8080


# hello.ihateiceforfree.com


# docker build . -t static-sites-hello
# docker run static-sites-hello -d -p 8080:80