FROM python:3.13-alpine

# https://hub.docker.com/_/python


# FROM ubuntu:22.04

# https://github.com/docker-library/python/blob/3f2d7e4c339ab883455b81a873519f1d0f2cd80a/3.13/alpine3.22/Dockerfile


# https://github.com/astral-sh/uv/issues/6392


